id: A44646430
title: The Sūtra of Boundless Life and Wisdom
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:08:25.681517
  last_modified_at: 2022-03-01 02:08:25.681520
