id: A44646430
title: Prayer for the Future of the Dharma
type: translation
source_metadata:
  languages:
  - en
  - es
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:08:25.611536
  last_modified_at: 2022-03-01 02:08:25.611539
