id: A44646430
title: Verses of Confession 'Düsum Deshekma'
type: translation
source_metadata:
  languages:
  - en
  - de
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:08:25.691239
  last_modified_at: 2022-03-01 02:08:25.691242
