id: A44646430
title: The Song of the Vajra
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:08:25.678852
  last_modified_at: 2022-03-01 02:08:25.678855
