id: A44646430
title: The Heart of the Transcendent Perfection of Wisdom
type: translation
source_metadata:
  languages:
  - en
  - es
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:08:25.624016
  last_modified_at: 2022-03-01 02:08:25.624019
