id: A44646430
title: Vajravidāraṇa Dhāraṇī (Nyingma Version)
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:08:25.687991
  last_modified_at: 2022-03-01 02:08:25.687994
