id: A44646430
title: The Noble Sūtra of Recalling the Three Jewels
type: translation
source_metadata:
  languages:
  - en
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:08:25.640522
  last_modified_at: 2022-03-01 02:08:25.640525
