id: A44646430
title: Maitreya's Aspiration
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:08:25.608149
  last_modified_at: 2022-03-01 02:08:25.608152
