id: A44646430
title: The Noble Dhāraṇī of The Supreme Accomplishment of Sitātapatrā Born from the
  Tathāgata’s Uṣṇīṣa, the Great Invincible Dispeller
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:08:25.635688
  last_modified_at: 2022-03-01 02:08:25.635692
