id: A44646430
title: The Perfection of Wisdom, Mother of All Tathāgatas, ‘In One Syllable’
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:08:25.641808
  last_modified_at: 2022-03-01 02:08:25.641811
