id: A44646430
title: The Noble Incantation entitled ‘The Rituals for the Blue-Clad Vajrapāṇi’
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:08:25.637403
  last_modified_at: 2022-03-01 02:08:25.637406
