id: A44646430
title: The Bodhisattva’s Confession of Downfalls (Nyingma Version)
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:08:25.615047
  last_modified_at: 2022-03-01 02:08:25.615049
