id: A44646430
title: 'The King of Aspiration Prayers: Samantabhadra''s “Aspiration to Good Actions”
  (Zangchö Mönlam)'
type: translation
source_metadata:
  languages:
  - en
  - es
  - fr
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:08:25.629964
  last_modified_at: 2022-03-01 02:08:25.629967
